### ISSUE TITLE
To create anything, creates Chinese characters

### ISSUE THREAD

**Issue by nefcanto** [moodmosaic/Fare#13]
I'm trying to get a random string. Anything is acceptable. Thus I came with this regular expression:

.*

That literally means any character, any number of times.

However, I ran this line of code like a thousand times, and not even once I get a simple English character, all gibberish and Chinese. 

new Fare.Xeger(".*").Generate(); // ran for a thousand times, and I expected outputs like "A坏_#@la", but I got examples like "☐缨坏庶袗"

Why is it behaving that way? Does it have an internal preference for Unicode characters? Does it ignore ASCII characters on string generation, unless explicitly force via the Regular Expression pattern?

**Comment by moodmosaic** [comment]
Thank you for reporting this!

Project Fare turns Regular Expressions into [Automatons](http://en.wikipedia.org/wiki/Deterministic_finite_automaton) by applying the algorithms of [dk.brics.automaton](http://www.brics.dk/automaton/) and [xeger](https://code.google.com/p/xeger/).

Unfortunately, I don't have an answer to your question, as Project Fare is really a port of the above Java projects.

You may use a different pattern or use a different *engine* to reverse the Regular Expression into an Automaton. As an example, you can use the [Rex](http://research.microsoft.com/en-us/projects/rex/) engine.

**Comment by ejs09f** [comment]
I'm running into this issue too.  I don't suppose either of you figured out why we're getting Chinese characters?  Thanks!

**Comment by moodmosaic** [comment]
@edwardskrod, this is a wild guess, but I'm thinking whether it's because of some encoding issue that slipped through while I was porting the code from the Java version...

I'd be curious to find out if this is the case also in the Java version, which means I'd first have to install Java and a Java-capable IDE on my machine, so I can compare with the [original Java versions](https://github.com/moodmosaic/Fare/issues/13#issuecomment-109788197)...

**Comment by edwardskrod** [comment]
@moodmosaic We were able to run the .jar from https://code.google.com/archive/p/xeger/downloads using the following Regex:  ^([^ A-Z]+)$ 

It looks like the issue is in the original Java code as well.

I believe this is because they are using the Unicode character set to generate characters. 

Interestingly enough, the generated string will validate when you call Regex.Validate and pass the generated string and the regex.

![d9bd5502](https://user-images.githubusercontent.com/5585130/32233612-06fcc55e-be18-11e7-99bb-dc1ed5290844.PNG)

**Comment by moodmosaic** [comment]
@edwardskrod, thank you for trying this also in the Java version. At this point, I think we could deviate from the Java version, and perhaps use ASCII, or some Unicode subset that will generate readable characters.

**Comment by edwardskrod** [comment]
@moodmosaic   I'll take a look.  My first priority is to figure out how to solve the Stack Overflow exception generated by certain regular expressions.  I'll let you know if I figure it out.

**Comment by moodmosaic** [comment]
@edwardskrod, sounds good.
