### ISSUE TITLE
Repetitive generation returns same result at high speed

### ISSUE THREAD

**Issue by nefcanto** [moodmosaic/Fare#14]
Hi,

I'm generating like 5000 instances of data using Fare in parallel. From some point onward the results get repetitive.

The code is:

static Xeger persianWordPattern = new Xeger(@"[آ ا ب پ ت ج چ ح خ د ذ ر ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن و ه ی]{2,8}");

And in a parallel loop, after a while the results would become:

آآ
آآ
آآ
آآ
آآ
آآ
آآ
آآ

Any idea why this is so?

Thank you for this great library.

**Comment by moodmosaic** [comment]
Thank you for reporting this! It looks weird to me as well, and I can't currently think a solution to this.

Have you tried with a different pattern?

**Comment by nefcanto** [comment]
Yeah, actually I thought maybe it's because of the Unicode characters. Thus I tried [a-z]{3,10} too, and it also has the same problem.

**Comment by moodmosaic** [comment]
Looks like a session with the debugger is warranted :smile: – I'll let you know if I found a solution to this.

**Comment by nefcanto** [comment]
Thank you. This library is really useful. Removing these bugs is worth it. I would be pleased to help.

**Comment by moodmosaic** [comment]
You're welcome to help, by sending Pull Request(s)! Also, feel free to ask questions – please keep in mind that I might not have all the answers :smiley:

**Comment by DanyO** [comment]
@nefcanto 
A workaround for this issue would be to initialize Xeger with an outside Random object instead of letting Zeger use and declare its own. (using the constructor Xeger(expression, random)). The Random() object should only be initialized once and not on every call/thread.

Also, you might want to consider Instantiating Xeger() only once and not for every call/thread.

The reason for this is because Random() uses the Environment.TickCount property to seed the random values generator. On most systems the resolution of a Tick is about 10ms to 16ms, so if Random() is initialized more than once during that 10ms-16ms time period, it will spit out the name suite of numbers which in this case results in choosing the same character over and over.

By providing Xeger() with a Random() object initialized outside of the tight loop or parallel operation (as my above example workaroud attempts to do) you would not have that problem.

**Comment by moodmosaic** [comment]
Very nice. That's actually the idiomatic way of making `Random` less deterministic in .NET, so I'm going to close this one. Feel free to reopen if needed.
