### ISSUE TITLE
Inifinite loop processing expression

### ISSUE THREAD

**Issue by sprotty** [moodmosaic/Fare#15]
The sample code below causes FARE to enter an infinite loop, the problem is in BasicOperations.Determinize. I don't follow the code, but it looks like the bug maybe that its not stopping in the accept check (the break drops out of the for loop not the outer while loop).

     while(...)
     {
              ...
              foreach (State q in s)
                {
                    if (q.Accept)
                    {
                        r.Accept = true;
                        break; (I THINK THIS SHOULD BREAK OUT OF THE WHILE LOOP)
                    }
                }

Sample code

      string pattern = "\\S+.*";
      Fare.Xeger sut = new Fare.Xeger(pattern, rnd);

**Comment by moodmosaic** [comment]
Thank for reporting this :+1: This looks like a bug.

It's been a while since I looked into the source code, which is a [port of Java](http://blog.nikosbaxevanis.com/2011/11/19/notes-from-porting-java-code-to-net/)'s [dk.brics.automaton](http://www.brics.dk/automaton/), and so it might take a while before I report back. :neutral_face:

**Comment by moodmosaic** [comment]
This is now fixed and available as [Fare 1.0.1](https://www.nuget.org/packages/Fare/).

**Comment by sprotty** [comment]
Great, I'll give it s go tomorrow. Thanks for the amazing turn around

Cheers Simon
